services:
  web:
    container_name: hanavi_schedule_web
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../.env.local
